# configuration/production.yaml
application:
  host: "0.0.0.0"
  port: 8000
database:
  host: "db"
  port: 5432
  username: "postgres"
  database_name: "newsletter"
  require_ssl: true
  # Password is left out—we'll inject it!
# production.yaml
email_client:
  base_url: "https://live.api.mailtrap.io"
  sender_email: "sam.torres@realemail.com"
  mailtrap_account_id: "4443384" # Will be diff for prod instance if I go live with this
  timeout_milliseconds: 5000 # Faster timeout for production
  # authorization_token is OMITTED here because we
  # will inject it via APP_EMAIL_CLIENT__AUTHORIZATION_TOKEN
